global:
  scrape_interval: 5s
  scrape_timeout: 2s
  evaluation_interval: 5s


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'node-exporter'
    static_configs:
      - targets: [ '223.130.159.67:9100' ]
        labels:
          hostname: "dj-master-server"
      - targets: [ '10.0.20.6:9100' ]
        labels:
          hostname: "dj-server1" 

  - job_name: 'cadvisor'
    static_configs:
      - targets: 
          - '223.130.159.67:9101'
      - targets: 
          - '10.0.20.6:9101'
